### ISSUE TITLE
Error nil

### ISSUE THREAD

**Issue by loyalldo** [nicklaw5/helix#21] opened 2018-12-24 16:03 UTC
Hey Hey,
is it a Bug, that you return everytime a nil as error. It will be a fatal NullPointer exception and the catch of errors will be triggert. 

Greeting
Marcel 

https://github.com/nicklaw5/helix/blob/a74e7ff1098e73e6aa1944642d369e32c29c499d/helix.go#L110

**Comment by nicklaw5** [comment] 2018-12-26 17:31
The zero value of an error is nil. I'm not sure what you mean by "NullPointer" exception?

**Comment by nicklaw5** [comment] 2018-12-30 20:18
Closing. Please re-open if you are still experiencing issues.

**Closed by nicklaw5** 2018-12-30 20:18 UTC
Labels: question

**Comment by loyalldo** [comment] 2019-01-03 21:38
Sry i should not work sick... You´re totally correct. 
But than i have a Question to the Webhook. 
I get this Response. I think the WebhookSubscriptions should not be empty? 


> {ResponseCommon:{StatusCode:200 Header:map[Server:[nginx] Expires:[0] Pragma:[no-cache] Ratelimit-Limit:[800] Twitch-Trace-Id:[6d466f552f04c243125b5142fd8251c5] Vary:[Accept-Encoding] Front-End-Https:[on] Content-Type:[application/json; charset=utf-8] Access-Control-Allow-Origin:[*] Ratelimit-Remaining:[799] X-Ctxlog-Logid:[1-5c2e7e1e-e385ad0c28ec85f2a7291c06] Timing-Allow-Origin:[https://www.twitch.tv] Date:[Thu, 03 Jan 2019 21:26:55 GMT] Cache-Control:[no-cache, no-store, must-revalidate, private] Ratelimit-Reset:[1546550815]] Error: ErrorStatus:0 ErrorMessage:} Data:{Total:0 WebhookSubscriptions:[] Pagination:{Cursor:}}}

**Comment by nicklaw5** [comment] 2019-01-03 21:47
By the looks of it you don't have any subscriptions. This is working as intended. I am currently using it in production and it's working fine.

It may be that you are not verifying the webhook subscription. I suggest you follow the [webhook example flow](https://dev.twitch.tv/docs/api/webhooks-reference/#example-of-webhook-flow) that Twitch provides.

**Comment by nicklaw5** [comment] 2019-01-03 21:54
I did make [this small adjustment](https://github.com/nicklaw5/helix/commit/30ddc8740dc76a5c64925deedb1b553fe1f23df6) earlier today. So is you are using secrets as part of your webhook workflow, that may have been the reason why you might not have been able to validate a webhook subscription.

**Comment by loyalldo** [comment] 2019-03-10 16:33
i tried to follow your docs example for Webhooks. 
I cant find my Failure. Could you show me you´re live Example?
